
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//
// (edit version number in the .version file)

using System.Reflection;

[assembly: AssemblyVersion("2.0.0.0")] // only the major version gets changed
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: KSPAssembly("TargetInterceptPlanner", 2, 0, 0)]
[assembly: KSPAssemblyDependency("ClickThroughBlocker", 1, 0)]
[assembly: KSPAssemblyDependency("HarmonyKSP", 1, 0)]
[assembly: KSPAssemblyDependency("ToolbarController", 1, 0)]